### PR TITLE
Add sections 3 & 4 to COVID Declaration form

### PR DESCRIPTION
**Pull request by john12321**
- Add COVID declaration form sections 3 & 4
- Fix form validation bug where validation lags behind change event (e.g. validation msg remained after field checked)
- Fix bug in COVID section and other sections so change event which hides a field also resets its value and therefore stops data persisting and being saved to db)

TICKET: TISNEW-4946

### CODE REVIEW

**Comment by heetis-shivanirana** [comment]
@john12321 apologies If I am wrong but I am not able to see the e2e test related to Formr-b covid section 3 and 4. There is only two files I can see related to e2e test ( formr-a.spec.ts  and cypress/support/commands.js ). I am expecting we have test related to formr-b covid section in form-b.spec.ts.

**Comment by john12321** [comment]
> @john12321 apologies If I am wrong but I am not able to see the e2e test related to Formr-b covid section 3 and 4. There is only two files I can see related to e2e test ( formr-a.spec.ts and cypress/support/commands.js ). I am expecting we have test related to formr-b covid section in form-b.spec.ts.

**Comment by john12321** [comment]
@heetis-shivanirana No worries. The tests are written in the **cypress/support/commands.js file** and are called in the **form-b.spec.ts** via the command: **cy.checkAndFillCovidSection()**

**Comment by heetis-shivanirana** [comment]
> @heetis-shivanirana No worries. The tests are written in the **cypress/support/commands.js file** and are called in the **form-b.spec.ts** via the command: **cy.checkAndFillCovidSection()**

**Comment by heetis-shivanirana** [comment]
@john12321 Thanks for the reply. I am not able to see form-b.spec.ts in this commit. Are you able to see that file?

**Comment by Judge40** [comment]
> @john12321 Thanks for the reply. I am not able to see form-b.spec.ts in this commit. Are you able to see that file?

I don't think there were any changes need to `form-b.spec.ts` as it already calls `cy.checkAndFillCovidSection()` https://github.com/Health-Education-England/trainee-ui/blob/master/cypress/integration/formr-b/formr-b.spec.ts#L151

**Comment by heetis-shivanirana** [comment]
Sorry @john12321 by mistake while commenting I closed the pull request but it has reopened again.

**Comment by john12321** [comment]
@heetis-shivanirana No worries. Had me worried there! @Judge40 Cheers!

**Pull request merged**
